### PR TITLE
Token Stake Optimizations

### PR DESCRIPTION
**Pull request by WhiteOakKong**
Changes:

- Update struct `Staker`
     - uint256 `conditionIdOflastUpdate` => uint64 `conditionIdOflastUpdate`
     - uint256 `timeOfLastUpdate => uint128 `timeOfLastUpdate`
     - Other associated changes to facilitate use of updated struct
- Update struct `StakingCondition`
     - uint256 `timeUnit` => uint80 `timeUnit`
     - uint256 `startTimestamp` => uint80 `startTimestamp`
     - uint256 `endTimestamp` => uint80 `endTimestamp`
     - Other associated changes to facilitate use of updated struct
- Remove stakersArray (stakersArray doesn't appear to provide any function outside of easy access to a full list of active stakers).
- Reduce size of `stakingTokenDecimals` and `rewardTokenDecimals` to allow for efficient variable packing
- Reorder variables in Staking20.sol and Staking20Upgradeable.sol
- Mark `stakingTokenDecimals`, `rewardTokenDecimals`, and `stakingToken` as immutable in Staking20.sol

These changes result in:

27% reduction in gas consumption in the stake function
15% reduction in gas consumption in the withdraw function
10% reduction in gas consumption in the claimRewards function.

### CODE REVIEW

**Comment by nkrishang** [comment]
Hey @WhiteOakKong love the PR, we're onto reviewing it. If you can get the code to pass the PR checks (and pending our internal review, which we'd communicate here), we can then merge it 🚢

**Comment by WhiteOakKong** [comment]
Thanks @nkrishang. I just ran it through the linting, so hopefully that fixes the check.

**Comment by nkrishang** [comment]
Amazing, thanks! We're developing our gas optimization bounty program and would love to kickstart it with this PR. 

Could you run `forge build` and then `yarn gas`, and commit the changes? This will populate the `gasreport.txt` (based on the benchmark tests in `src/test/benchmark`) and reflect the relevant changes in gas we want to measure.

**Comment by WhiteOakKong** [comment]
All set. 

For future reference, is this the style of PR you prefer? I opened a couple (#417 #416) right before this that were split a bit smaller in scope (IE both were optimizations on the same base contract but were different fundamental changes), but I think the scope of this PR is probably more ergonomic. If you agree, I'll combine those two.

**Pull request merged**
