### PR TITLE
Added benchmark tests for smart-wallet

### PR DESCRIPTION
**Pull request by alfheimrShiven**
Includes benchmark tests for non-upgradable smart accounts. Following are the gas measurements:
PASS] test_state_accountReceivesNativeTokens() (gas: 11012)
[PASS] test_state_addAndWithdrawDeposit() (gas: 83248)
[PASS] test_state_contractMetadata() (gas: 59240)
[PASS] test_state_createAccount_viaEntrypoint() (gas: 428384)
[PASS] test_state_createAccount_viaFactory() (gas: 334603)
[PASS] test_state_executeBatchTransaction() (gas: 40271)
[PASS] test_state_executeBatchTransaction_viaAccountSigner() (gas: 392267)
[PASS] test_state_executeBatchTransaction_viaEntrypoint() (gas: 83624)
[PASS] test_state_executeTransaction() (gas: 35783)
[PASS] test_state_executeTransaction_viaAccountSigner() (gas: 377498)
[PASS] test_state_executeTransaction_viaEntrypoint() (gas: 75957)
[PASS] test_state_receiveERC1155NFT() (gas: 39331)
[PASS] test_state_receiveERC721NFT() (gas: 78307)
[PASS] test_state_transferOutsNativeTokens() (gas: 82073)

### CODE REVIEW

**Comment by kumaryash90** [comment]
@alfheimrShiven thanks for the PR!
we're taking a look, and will get back to you asap

**Comment by alfheimrShiven** [comment]
> @alfheimrShiven thanks for the PR! we're taking a look, and will get back to you asap

Sure @kumaryash90. Thanks for the update.

**Comment by WhiteOakKong** [comment]
@alfheimrShiven Could you give me permission to push to your branch? We are good to merge, I just fixed a few things to align with our recent signer perms changes.

**Review by kumaryash90 — APPROVED** [review]

**Comment by alfheimrShiven** [comment]
> @alfheimrShiven Could you give me permission to push to your branch? We are good to merge, I just fixed a few things to align with our recent signer perms changes.

Hey @WhiteOakKong I guess @kumaryash90 has incorporated the change. Thank you.

**Pull request merged**
