### PR TITLE
Open pack gas bounty

### PR DESCRIPTION
**Pull request by kien-ngo**
- [x] Caching `variable.length`
- [x] `unchecked { ++i; }`
- [x] `uint256 variable = 0;` -> `uint256 variable;`
- [x] No change to contract interface

Gas saved:
image

### CODE REVIEW

**Comment by nkrishang** [comment]
Hey @kien-ngo 👋🏽  l'd like to get your PR merged asap. Could you resolve merge conflicts and fix the lint error (attached screenshot). 

I believe you can resolve the `lib/chainlink` git modules conflict by running `foundryup` then `forge install`, once you've pulled the base branch.

**Comment by kien-ngo** [comment]
Ok boss

**Comment by kien-ngo** [comment]
@nkrishang Hey mate, running `yarn gas` on my machine (Windows 10) doesn't produce the same gasreport layout as the one from the main repo.

Before that I have run the `foundryup` and `forge install` like you said. Here's my current version;
image


Should I just manually copy the value over, since I only worked on 1 function anyway?

**Comment by kien-ngo** [comment]
Done. Please review @nkrishang ^^

**Pull request merged**
