### PR TITLE
Erc20bases update: remove _contractURI from constructor params

### PR DESCRIPTION
**Pull request by kumaryash90**

### CODE REVIEW

**Review by joaquim-verges — APPROVED** [review]
Ship it

**Comment by joaquim-verges** [comment]
Lets make a new release with this to put on the CLI

**Comment by joaquim-verges** [comment]
@kumaryash90 can you make the change in CLI as well so the templates constructor match this change?

**Comment by kumaryash90** [comment]
> ###

okay

**Pull request merged**
